$projectRoot = "e:\WebGL_tesis\desarrollo\unity_project"
$assetsPath = "$projectRoot\Assets"
$generatedPath = "$assetsPath\Scripts\UI\Generated"

Write-Host "`n[STARTING UI VALIDATION]`n" -ForegroundColor Cyan

# Ensure Generated Directory Exists
if (-not (Test-Path $generatedPath)) {
    New-Item -ItemType Directory -Force -Path $generatedPath | Out-Null
}

# 1. USS VALIDATION
Write-Host "1. Scanning USS Files..." -ForegroundColor Yellow
$ussFiles = Get-ChildItem -Path $assetsPath -Include *.uss -Recurse
foreach ($file in $ussFiles) {
    $content = Get-Content $file.FullName
    $lineNum = 0
    foreach ($line in $content) {
        $lineNum++
        # Deep Nesting Check (Heuristic: counting spaces/combinators)
        # Matches 4 or more segments separated by space or >
        if ($line -match "([^\s>]+[\s>]+){4,}") {
             Write-Host "   ⚠️ [USS] $($file.Name):$lineNum - Deep nesting detected (>3 levels). Performance risk." -ForegroundColor Yellow
        }
        # Shorthand usage
        if ($line -match "transition:\s*.*ease") {
            Write-Host "   ⚠️ [USS] $($file.Name):$lineNum - 'ease' in shorthand transition. (Unity 6 Incompatible)" -ForegroundColor Yellow
        }
    }
}

# 2. BINDING GENERATION
Write-Host "`n2. Generating UI Constants..." -ForegroundColor Yellow
$uxmlFiles = Get-ChildItem -Path $assetsPath -Include *.uxml -Recurse
$allNames = @()

foreach ($file in $uxmlFiles) {
    $content = Get-Content $file.FullName
    # Find name="..." 
    $names = [regex]::Matches($content, 'name="([^"]+)"') | ForEach-Object { $_.Groups[1].Value }
    $allNames += $names
}

$uniqueNames = $allNames | Select-Object -Unique | Sort-Object

$csContent = @"
// <auto-generated>
// This file is generated by the Antigravity UI Validator Skill.
// Do not modify manually.
// </auto-generated>

namespace WebGL.UI.Generated
{
    public static class UIConstants
    {
"@

foreach ($name in $uniqueNames) {
    # Sanitize variable name (remove - or spaces)
    $varName = $name -replace "[- ]", "_"
    $csContent += "`n        public const string $varName = `"$name`";"
}

$csContent += @"
    }
}
"@

$outFile = "$generatedPath\UIConstants.cs"
$csContent | Out-File $outFile -Encoding UTF8
Write-Host "   ✅ Generated $($uniqueNames.Count) UI constants in $outFile" -ForegroundColor Green

Write-Host "`n[UI VALIDATION COMPLETE]`n" -ForegroundColor Cyan
